// Generated by CoffeeScript 1.9.2
(function() {
  var Streamer, rStream, util;

  util = require('util');

  rStream = require('stream').Transform;

  Streamer = function(opts) {
    if (opts == null) {
      opts = {};
    }
    rStream.call(this, {
      highWaterMark: 2,
      readableObjectMode: true,
      writableObjectMode: true
    });
    this.n = 0;
    this.bufs = [];
    this.opts = opts;
    if (opts.setup) {
      this.opts.setup.call(this);
    }
    return this;
  };

  util.inherits(Streamer, rStream);

  Streamer.prototype.lastConvert = function() {
    return this.push(null);
  };

  Streamer.prototype._flush = function() {
    return this.lastConvert();
  };

  Streamer.prototype._transform = function(chunk, encoding, cb) {
    return this.convert(chunk, cb);
  };

  module.exports = Streamer;

}).call(this);
